BookReadingWebApp/Controllers/CommentController.cs
using BookReadingApp.Application.Interfaces;
using BookReadingApp.Core.Modals;
using FacadePattern.FacadeInterface;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookReadingApp.Web.Controllers
{
    public class CommentController : Controller
    {
        //private readonly ICommentRepository _commentPageService;
        //public CommentController(ICommentRepository commentPageService)
        //{
        //    _commentPageService = commentPageService;
        //}
        private readonly ICommentFacade _commentPageService;
        public CommentController(ICommentFacade commentPageService)
        {
            _commentPageService = commentPageService;
        }
        public async Task<IActionResult> GetComments()
        {
            var commentList = await _commentPageService.GetComments();
            return View(commentList);
        }
        public async Task<IActionResult> ViewComment(int id)
        {
            var comment = await _commentPageService.ViewComment(id);
            if (comment == null)
            {
                return RedirectToAction("GetComments");
            }
            return View(comment);
        }

        //POST :- CommentController/Create
        [HttpPost]
        public async Task<IActionResult> PostComment(Comment commentViewModel)
        {
            var result = await _commentPageService.PostComment(commentViewModel);
            return RedirectToAction("ViewDetails", "Event", new { id = commentViewModel.EventId });
        }
    }
}

BookReadingWebApp/Controllers/EventController.cs
using System.Threading.Tasks;
using BookReadingApp.Application.Interfaces;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using BookReadingApp.Core.Modals;
using FacadePattern.FacadeInterface;

namespace BookReadingApp.Web.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventFacade _eventPageService;
        private readonly ICommentFacade _commentPageService;
        private IEventRepository eventPageService;
        private ICommentRepository commentPageService;

        public EventController(IEventFacade eventPageService, ICommentFacade commentPageService)
        {
            _eventPageService = eventPageService ?? throw new ArgumentNullException(nameof(eventPageService));
            _commentPageService = commentPageService ?? throw new ArgumentNullException(nameof(commentPageService));
        }

        public EventController(IEventRepository eventPageService, ICommentRepository commentPageService)
        {
            this.eventPageService = eventPageService;
            this.commentPageService = commentPageService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("Events")]
        public async Task<IActionResult> GetEvents()
        {
            var eventList = await _eventPageService.GetEvents();
            return View(eventList);
        }

        [Route("Events/{id}")]
        public async Task<IActionResult> ViewDetails(int? id)
        {
            var details = await _eventPageService.ViewDetails(id.Value);
            var ans = await _eventPageService.GetAllCommentByEventId(id.Value);
            details.Comments = ans;
            if (details == null)
            {
                return RedirectToAction("GetEvents");
            }
            return View(details);
        }

        [Authorize]
        [Route("CreateEvent")]
        public IActionResult CreateEvent()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("CreateEvent")]
        public async Task<IActionResult> CreateEvent(Event eventViewModel)
        {
            var result = await _eventPageService.CreateEvent(eventViewModel);
            if (result > 0)
            {
                return RedirectToAction(nameof(CreateEvent));
            }
            return View();
        }

        [Authorize]
        [Route("UpdateEvent/{id}")]
        public async Task<IActionResult> UpdateEvent(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("GetEvents");
            }
            var ans = await _eventPageService.ViewDetails(id.Value);

            if (ans == null)
            {
                return RedirectToAction("GetEvents");
            }
            return View(ans);
        }

        [Authorize]
        [HttpPost]
        [Route("UpdateEvent/{id}")]
        public IActionResult UpdateEvent(Event eventViewModel)
        {
            var _id = _eventPageService.UpdateEvent(eventViewModel);
            if (_id > 0)
            {
                return RedirectToAction("ViewDetails", new { id = _id });
            }
            return View();
        }

        [Authorize]
        [Route("MyEvents")]
        public async Task<IActionResult> MyEvents()
        {
            var organiser = User.Identity.Name;
            var eventList = await _eventPageService.MyEvents(organiser);
            return View(eventList);
        }

        [Authorize]
        [Route("EventsInvitedTo")]
        public async Task<IActionResult> EventsInvitedTo()
        {
            var eventList = await _eventPageService.GetEvents();
            return View(eventList);
        }

        [Route("FetchComments/{_id}")]
        public async Task<IActionResult> GetAllCommentByEventId(int _id)
        {
            var ans = await _eventPageService.GetAllCommentByEventId(_id);
            if (ans == null)
            {
                return RedirectToAction("ViewDetails", new { id = _id });
            }
            return View(ans);
        }
    }
}

BookReadingWebApp/Views/Shared/_CommentBox.cshtml
@model BookReadingApp.Core.Modals.Comment

<h4>Comment</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Comment" asp-action="PostComment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventId" class="custom-control-label"></label>
                <input asp-for="EventId" class="form-control" />
                <span asp-validation-for="EventId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="comment" class="custom-control-label"></label>
                <input asp-for="comment" class="form-control" />
                <span asp-validation-for="comment" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Post" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

BookReadingWebApp/Views/Shared/_DisplayEvents.cshtml
@model IList<BookReadingApp.Core.Modals.Event>

<div class="container">
    <div class="container">
        <h3 class="text-success">Upcoming Events</h3>
        <hr class="border-dark" />

        <div class="row">
            @foreach (var item in Model)
            {
                if (item.Date > DateTime.Now)
                {
                    <partial name="_EventFirst" model="@item" />
                }
            }
        </div>
    </div>

    <div class="container">
        <h3 class="text-success"> Past Events</h3>
        <hr class="border-dark" />

        <div class="row">
            @foreach (var item in Model)
            {
                if (item.Date < DateTime.Now)
                {
                    <partial name="_EventFirst" model="@item" />
                }

            }

        </div>

    </div>

</div>

BookReadingWebApp/Views/Shared/_EventDetails.cshtml
@model BookReadingApp.Core.Modals.Event
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> _signInManager
@inject UserManager<IdentityUser> _userManager

@{
    var user = await _userManager.GetUserAsync(User);
    var email = "";
    if (user != null)
    {
        email = user.Email;
    }
}

<div class="col-md-4">
    <div class="card mb-4" style="width:20rem;">
        <div class="card-body">
            <div class="card-title">
                <h4>@Model.Title</h4>
            </div>

            <div>
                <p class="text-dark d-inline">Location :</p>@Model.Location
            </div>
            <div>
                <p class="text-dark d-inline">Date :</p>@Model.Date.ToShortDateString()
            </div>
            <div>
                <p class="text-dark d-inline">Start Time :</p>@Model.StartTime.ToShortTimeString();
            </div>

            <div class="btn-group">
                <a asp-controller="Event" asp-action="ViewDetails" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-primary"> View Details</a>
            </div>

            @if (_signInManager.IsSignedIn(User) && (User.Identity.Name == Model.Organiser || email == "myadmin@bookevents.com") && Model.Date >= DateTime.Now)
            {
                <div class="btn-group">
                    <a asp-controller="Event" asp-action="UpdateEvent" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-primary">Update Details</a>
                </div>
            }

            <div class="row">
                <div class="co-md-6">
                    <p class="text-danger"> @Model.EventType Event</p>
                </div>
                <div class="col-md-6 text-danger"> Organised By <b>@Model.Organiser</b></div>
            </div>

        </div>
    </div>
</div>

BookReadingWebApp/Views/Shared/_EventDetailsIndexPage.cshtml
@model BookReadingApp.Core.Modals.Event
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> _signInManager
@inject UserManager<IdentityUser> _userManager
@{
    var user = await _userManager.GetUserAsync(User);
    var email = user != null ? user.Email : "";

}

<div class="container">
    <div class="container">
        <div class="col-md-12">
            <div>
                <div class="card-body">
                    <div class="card-title">
                        <h4>@Model.Title </h4>
                    </div>

                    <div>
                        <p class="text-dark d-inline">Location :</p>@Model.Location
                    </div>
                    <div>
                        <p class="text-dark d-inline">Date :</p> @Model.Date.ToShortDateString()
                    </div>
                    <div>
                        <p class="text-dark d-inline">Start Time :</p> @Model.StartTime.ToShortTimeString()
                    </div>

                    <div class="btn-group">
                        <a asp-action="ViewDetails" asp-controller="Event" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-primary">View Details</a>
                    </div>
                    <p></p>
                    @if (_signInManager.IsSignedIn(User) && (User.Identity.Name == Model.Organiser || email == "myadmin@bookevents.com") && Model.Date >= DateTime.Now)
                    {
                        <p></p>
                        <div class="btn-group">
                            <a asp-action="UpdateEvent" asp-route-id="@Model.Id" asp-controller="Event" class="btn btn-sm btn-outline-primary">Update Details</a>
                        </div>
                        <p></p>
                    }

                    <div class="row">
                        <div class="col-md-6">
                            <p class="text-danger">@Model.EventType Event</p>
                        </div>
                        <div class="col-md-6 text-danger">Organised by <b>@Model.Organiser</b></div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

BookReadingWebApp/Views/Shared/_EventFirst.cshtml
@model BookReadingApp.Core.Modals.Event

@if (Model.StartTime < DateTime.Now)
{
    <partial name="_EventDetails" model="@Model" />
}
else
{
    <partial name="_EventDetails" model="@Model" />
}

BookReadingWebApp/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<IdentityUser> _signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookReadingWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookReading</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <partial name="_LoginInfo" />
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="GetEvents">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CustomerSupport">Customer Support</a>
                        </li>

                        @if (_signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="CreateEvent">Create Event</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="MyEvents">My Event</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="EventsInvitedTo">Events Invited To</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Copyright &copy;- BookReading - @DateTime.Now.Year
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookReadingWebApp/Views/Shared/_LoginInfo.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> _signInManager


<ul class="navbar-nav">
    @if (_signInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-dark">Hello @User.Identity.Name!</a>
        </li>
        <li class="nav-item">
            <a class="nav-link btn btn-link text-dark" asp-action="LogOut" asp-controller="Account">Logout</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Account" asp-action="SignUp">Register</a>
        </li>
    }
</ul>
